-- 19. 동점자 처리 기준 필터(파라미터)
SELECT
  AI.IPSIYEAR as "입시연도"
  , AI.IPSIGUBUN as "모집시기"
  , AI.SELTYPENAME as "모집전형"
  , AI.MAJORNAME as "모집단위"
  , AI.SUHUMNO as "수험번호"
  , AI.LASTCONVERTSCORE as "전형총점"
  , AI.LASTRANK as "순위"
  , AMT_2.TS1 as "처리기준1"
  , AMT_2.TS2 as "처리기준2"
  , AMT_2.TS3 as "처리기준3"
  , AMT_2.TS4 as "처리기준4"
  , AMT_2.TS5 as "처리기준5"
  , AMT_2.TS6 as "처리기준6"
  , AMT_2.TS7 as "처리기준7"
  , AMT_2.TS8 as "처리기준8"
  , AMT_2.TS9 as "처리기준9"
  , AMT_2.TS10 as "처리기준10"
FROM VWAPPLYINFO AI
INNER JOIN VWSELECTTYPESMIDX STM ON AI.IPSIYEAR = STM.IPSIYEAR AND AI.IPSIGUBUN = STM.IPSIGUBUN
  AND AI.GUNID = STM.GUNID AND AI.SELTYPECODE = STM.SELTYPECODE AND AI.MAJORCODE = STM.MAJORCODE
INNER JOIN APPLYINFOMASTERTIESCORE AMT_2 ON AI.IPSIYEAR = AMT_2.IPSIYEAR AND AI.IPSIGUBUN = AMT_2.IPSIGUBUN
  AND AI.SUHUMNO = AMT_2.SUHUMNO AND AMT_2.STEP = '2'
INNER JOIN (
  SELECT STM.IPSIYEAR, STM.IPSIGUBUN, STM.SMIDX, AM.LASTCONVERTSCORE
    , MAX(TS1) TS1_MAX, MIN(TS1) TS1_MIN
    , MAX(TS2) TS2_MAX, MIN(TS2) TS2_MIN
    , MAX(TS3) TS3_MAX, MIN(TS3) TS3_MIN
    , MAX(TS4) TS4_MAX, MIN(TS4) TS4_MIN
    , MAX(TS5) TS5_MAX, MIN(TS5) TS5_MIN
    , MAX(TS6) TS6_MAX, MIN(TS6) TS6_MIN
    , MAX(TS7) TS7_MAX, MIN(TS7) TS7_MIN
    , MAX(TS8) TS8_MAX, MIN(TS8) TS8_MIN
    , MAX(TS9) TS9_MAX, MIN(TS9) TS9_MIN
    , MAX(TS10) TS10_MAX, MIN(TS10) TS10_MIN
  FROM APPLYINFO AI
  INNER JOIN APPLYINFOMASTER AM ON AI.IPSIYEAR = AM.IPSIYEAR AND AI.IPSIGUBUN = AM.IPSIGUBUN
    AND AI.SUHUMNO = AM.SUHUMNO
  INNER JOIN APPLYINFOMASTERTIESCORE AMT ON AI.IPSIYEAR = AMT.IPSIYEAR AND AI.IPSIGUBUN = AMT.IPSIGUBUN
    AND AI.SUHUMNO = AMT.SUHUMNO AND AMT.STEP = '2'
  INNER JOIN VWSELECTTYPESMIDX STM ON AI.IPSIYEAR = STM.IPSIYEAR AND AI.IPSIGUBUN = STM.IPSIGUBUN
    AND AI.GUNID = STM.GUNID AND AI.SELTYPECODE = STM.SELTYPECODE AND AI.MAJORCODE = STM.MAJORCODE
  GROUP BY STM.IPSIYEAR, STM.IPSIGUBUN, STM.SMIDX, AM.LASTCONVERTSCORE
  HAVING COUNT(*) > 1
) SAME ON STM.IPSIYEAR = SAME.IPSIYEAR AND STM.IPSIGUBUN = SAME.IPSIGUBUN 
  AND STM.SMIDX = SAME.SMIDX AND AI.LASTCONVERTSCORE = SAME.LASTCONVERTSCORE
    AND {파라미터} = CASE WHEN {파라미터} = 0 THEN 0
            WHEN AMT_2.TS1 <> TS1_MIN THEN 1 WHEN AMT_2.TS1 <> TS1_MAX THEN 1 
            WHEN AMT_2.TS2 <> TS2_MIN THEN 2 WHEN AMT_2.TS2 <> TS2_MAX THEN 2 
            WHEN AMT_2.TS3 <> TS3_MIN THEN 3 WHEN AMT_2.TS3 <> TS3_MAX THEN 3 
            WHEN AMT_2.TS4 <> TS4_MIN THEN 4 WHEN AMT_2.TS4 <> TS4_MAX THEN 4 
            WHEN AMT_2.TS5 <> TS5_MIN THEN 5 WHEN AMT_2.TS5 <> TS5_MAX THEN 5 
            WHEN AMT_2.TS6 <> TS6_MIN THEN 6 WHEN AMT_2.TS6 <> TS6_MAX THEN 6 
            WHEN AMT_2.TS7 <> TS7_MIN THEN 7 WHEN AMT_2.TS7 <> TS7_MAX THEN 7 
            WHEN AMT_2.TS8 <> TS8_MIN THEN 8 WHEN AMT_2.TS8 <> TS8_MAX THEN 8 
            WHEN AMT_2.TS9 <> TS9_MIN THEN 9 WHEN AMT_2.TS9 <> TS9_MAX THEN 9 
            WHEN AMT_2.TS10 <> TS10_MIN THEN 10 WHEN AMT_2.TS10 <> TS10_MAX THEN 10 ELSE 0 END
WHERE AI.IPSIYEAR = {입학연도}
  AND AI.IPSIGUBUN = {모집시기}
ORDER BY AI.IPSIYEAR, AI.IPSIGUBUN, AI.SELTYPEORDER, AI.MAJORORDER, AI.LASTRANK