-- 2. 정시 모집/지원 현황(전날24시)_2025 이후
SELECT
    STM.IPSIYEAR "입학연도"
    , DECODE(GROUPING_ID(STM.IPSIYEAR, STM.IPSIGUBUN), 0, MAX(II.IPSINAME)) AS "모집시기"
    , DECODE(GROUPING_ID(STM.IPSIYEAR, STM.IPSIGUBUN), 0, MAX(IM.MAJORNAME), '합계') AS "모집학과명"
    , SUM(CASE WHEN STM.SELTYPECODE = '1060' THEN STM.PERSONNEL END) AS "일반전형_모집인원"
    , SUM(CASE WHEN STM.SELTYPECODE = '1060' THEN NVL(AI.APPLYCNT,0) END) AS "일반전형_지원인원"
    , CASE
        WHEN SUM(CASE WHEN STM.SELTYPECODE = '1060' THEN STM.PERSONNEL END) = 0 THEN 0
        ELSE ROUND(SUM(CASE WHEN STM.SELTYPECODE = '1060' THEN NVL(AI.APPLYCNT,0) END) / SUM(CASE WHEN STM.SELTYPECODE = '1060' THEN STM.PERSONNEL END), 2)
      END "일반전형_경쟁률"
    -- 정원내
    , SUM(CASE WHEN STM.SELTYPECODE = '1010' THEN STM.PERSONNEL END) "수능_모집인원"
    , SUM(CASE WHEN STM.SELTYPECODE = '1010' THEN NVL(AI.APPLYCNT,0) END) "수능_지원인원"
    , CASE
        WHEN SUM(CASE WHEN STM.SELTYPECODE = '1010' THEN STM.PERSONNEL END) = 0 THEN 0
        ELSE ROUND(SUM(CASE WHEN STM.SELTYPECODE = '1010' THEN NVL(AI.APPLYCNT,0) END) / SUM(CASE WHEN STM.SELTYPECODE = '1010' THEN STM.PERSONNEL END), 2)
      END "수능_경쟁률"
    , SUM(CASE WHEN STM.SELTYPECODE = '1020' THEN STM.PERSONNEL END) "학생부_모집인원"
    , SUM(CASE WHEN STM.SELTYPECODE = '1020' THEN NVL(AI.APPLYCNT,0) END) "학생부_지원인원"
    , CASE 
        WHEN SUM(CASE WHEN STM.SELTYPECODE = '1020' THEN STM.PERSONNEL END) = 0 THEN 0
        ELSE ROUND(SUM(CASE WHEN STM.SELTYPECODE = '1020' THEN NVL(AI.APPLYCNT,0) END) / SUM(CASE WHEN STM.SELTYPECODE = '1020' THEN STM.PERSONNEL END), 2)
      END "학생부_경쟁률"
    -- 정원외
    , SUM(CASE WHEN STM.SELTYPECODE = '2010' THEN STM.PERSONNEL END) "전문대졸_모집인원"
    , SUM(CASE WHEN STM.SELTYPECODE = '2010' THEN NVL(AI.APPLYCNT,0) END) "전문대졸_지원인원"
    , SUM(CASE WHEN STM.SELTYPECODE = '2020' THEN STM.PERSONNEL END) "농어촌_모집인원"
    , SUM(CASE WHEN STM.SELTYPECODE = '2020' THEN NVL(AI.APPLYCNT,0) END) "농어촌_지원인원"
    , SUM(CASE WHEN STM.SELTYPECODE = '2030' THEN STM.PERSONNEL END) "기초생활_모집인원"
    , SUM(CASE WHEN STM.SELTYPECODE = '2030' THEN NVL(AI.APPLYCNT,0) END) "기초생활_지원인원"
    , SUM(CASE WHEN STM.SELTYPECODE = '2040' THEN STM.PERSONNEL END) "서해5도_모집인원"
    , SUM(CASE WHEN STM.SELTYPECODE = '2040' THEN NVL(AI.APPLYCNT,0) END) "서해5도_지원인원"
    , SUM(CASE WHEN STM.SELTYPECODE = '2060' THEN STM.PERSONNEL END) "재직자_모집인원"
    , SUM(CASE WHEN STM.SELTYPECODE = '2060' THEN NVL(AI.APPLYCNT,0) END) "재직자_지원인원"
    , SUM(CASE WHEN STM.SELTYPECODE = '2070' THEN STM.PERSONNEL END) "외국인/북한이탈주민_모집인원"
    , SUM(CASE WHEN STM.SELTYPECODE = '2070' THEN NVL(AI.APPLYCNT,0) END) "외국인/북한이탈주민_지원인원"
    , SUM(CASE WHEN STM.SELTYPECODE = '2080' THEN STM.PERSONNEL END) "재외국민_모집인원"
    , SUM(CASE WHEN STM.SELTYPECODE = '2080' THEN NVL(AI.APPLYCNT,0) END) "재외국민_지원인원"

    -- 정원내, 정원외 통계
    , SUM(CASE WHEN STM.SELTYPEGUBUN = '1' THEN STM.PERSONNEL END) "정원내_모집인원"
    , SUM(CASE WHEN STM.SELTYPEGUBUN = '1' THEN NVL(AI.APPLYCNT,0) END) "정원내_지원인원"
    , CASE
        WHEN SUM(CASE WHEN STM.SELTYPEGUBUN = '1' THEN STM.PERSONNEL END) = 0 THEN 0
        ELSE ROUND(SUM(CASE WHEN STM.SELTYPEGUBUN = '1' THEN NVL(AI.APPLYCNT,0) END) / SUM(CASE WHEN STM.SELTYPEGUBUN = '1' THEN STM.PERSONNEL END), 2)
      END "정원내_경쟁률"
    , SUM(CASE WHEN STM.SELTYPEGUBUN = '2' THEN STM.PERSONNEL END) "정원외_모집인원"
    , SUM(CASE WHEN STM.SELTYPEGUBUN = '2' THEN NVL(AI.APPLYCNT,0) END) "정원외_지원인원"
    , CASE
        WHEN SUM(CASE WHEN STM.SELTYPEGUBUN = '2' THEN STM.PERSONNEL END) = 0 THEN 0
        ELSE ROUND(SUM(CASE WHEN STM.SELTYPEGUBUN = '2' THEN NVL(AI.APPLYCNT,0) END) / SUM(CASE WHEN STM.SELTYPEGUBUN = '2' THEN STM.PERSONNEL END), 2)
      END "정원외_경쟁률"
    -- 전체
    , SUM(STM.PERSONNEL) "전체_모집인원"
    , SUM(NVL(AI.APPLYCNT,0)) "전체_지원인원"
    , CASE
        WHEN SUM(STM.PERSONNEL) = 0 THEN 0
        ELSE ROUND(SUM(NVL(AI.APPLYCNT,0)) / SUM(STM.PERSONNEL), 2)
      END "전체_경쟁률"
FROM VWSELECTTYPEMODEL STM
INNER JOIN INFOIPSI II ON STM.IPSIYEAR = II.IPSIYEAR AND STM.IPSIGUBUN = II.IPSIGUBUN
INNER JOIN INFOMAJOR IM ON STM.IPSIYEAR = IM.IPSIYEAR AND STM.IPSIGUBUN = IM.IPSIGUBUN
  AND STM.MAJORCODE = IM.MAJORCODE
LEFT JOIN (
    SELECT IPSIYEAR, IPSIGUBUN, GUNID, SELTYPECODE, MAJORCODE
    , COUNT(*) AS APPLYCNT
    FROM APPLYINFO
    WHERE SUBSTR(APPLYTIME,1,8) <= TO_CHAR(SYSDATE,'YYYYMMDD') - 1
    GROUP BY IPSIYEAR, IPSIGUBUN, GUNID, SELTYPECODE, MAJORCODE
) AI ON STM.IPSIYEAR = AI.IPSIYEAR AND STM.IPSIGUBUN = AI.IPSIGUBUN
    AND STM.GUNID = AI.GUNID AND STM.SELTYPECODE = AI.SELTYPECODE AND STM.MAJORCODE = AI.MAJORCODE
WHERE STM.IPSIYEAR = {입학연도} AND STM.IPSIGUBUN = {모집시기} AND II.ISSIMUL = 0
GROUP BY ROLLUP((STM.IPSIYEAR, STM.IPSIGUBUN, STM.MAJORCODE))
ORDER BY STM.IPSIYEAR, STM.IPSIGUBUN, MAX(STM.MAJORORDER)