-- 6. 신입생모집 등록 현황(편입학)
SELECT
	CASE
		WHEN MAJORCODE LIKE '8%' THEN '2학년 1학기'
		WHEN MAJORCODE LIKE '6%' THEN '3학년 1학기' ELSE NULL
	END AS "편입학년"
	
	,CASE WHEN GROUPING(MAJORCODE) = 0 THEN MAX(MAJORNAME) ELSE '합 계' END AS "모집단위"
	, SUM(RECRUIT_TOTAL) AS 모집

	, SUM(INIT_EX_APPLY_TOTAL) AS 지원
	, SUM(INIT_EX_ENROLL_TOTAL) AS "등록(예정)"
	, SUM(RECRUIT_TOTAL - INIT_EX_ENROLL_TOTAL) AS 결원
	, SUM(IS_GIVEUP_TOTAL + IS_UN_REG_TOTAL) AS "예비포기+합격미등록"
	, SUM(INIT_EX_REFUND_TOTAL) AS "합격환불"
	, SUM(INIT_EX_APPLY_TOTAL - INIT_EX_ENROLL_TOTAL - IS_GIVEUP_TOTAL - IS_UN_REG_TOTAL - INIT_EX_REFUND_TOTAL) AS 잔여
	, CASE 
    WHEN SUM(RECRUIT_TOTAL) = 0 THEN 0
    ELSE TRUNC(SUM(INIT_EX_ENROLL_TOTAL) / SUM(RECRUIT_TOTAL) * 100, 1)
  END AS 등록률
		
	FROM(
	SELECT
		-- APPLYGRADE, APPLYTREM
		MAX(IM.MAJORNAME) AS MAJORNAME
		, IM.MAJORCODE
		, MAX(IM.DISPLAYORDER) AS DISPLAYORDER
		, MAX(STM.PERSONNEL) AS RECRUIT_TOTAL																								-- 모집인원
		
		, SUM(CASE WHEN AI.MAJORCODE IS NOT NULL THEN 1 ELSE 0 END) AS INIT_EX_APPLY_TOTAL  -- 지원
		, SUM(CASE WHEN AM.LastIsPass = 1 AND AM.IsReg = 1 AND (AM.ISREFUND = 0 OR AM.ISREFUND IS NULL) THEN 1 ELSE 0 END) AS INIT_EX_ENROLL_TOTAL		-- 등록(예정)
--		, SUM(CASE WHEN (AM.LastIsPass = 1 AND AM.IsReg = 0) OR AM.IsPassGiveup = 1 THEN 1 ELSE 0 END) AS INIT_EX_UN_ENROLL_TOTAL	-- 예비포기+합격미등록
    , SUM(CASE WHEN AM.LASTISPASS = 0 AND AM.ISPASSGIVEUP = 1 THEN 1 ELSE 0 END) AS IS_GIVEUP_TOTAL -- 예비포기인원
    , SUM(CASE WHEN AM.LASTISPASS = 0 AND AM.ISREG = 0 THEN 1 ELSE 0 END) AS IS_UN_REG_TOTAL -- 합격미등록
		, SUM(CASE WHEN AM.IsReg = 1 AND AM.IsRefund = 1 THEN 1 ELSE 0 END) + SUM(CASE WHEN AM.ISSAJUNG = 0 THEN 1 ELSE 0 END) AS INIT_EX_REFUND_TOTAL -- 합격환불(사정제외자 포함)

	FROM INFOMAJOR IM
		LEFT JOIN APPLYINFO AI
			ON IM.IPSIYEAR = AI.IPSIYEAR AND IM.IPSIGUBUN = AI.IPSIGUBUN AND IM.MAJORCODE = AI.MAJORCODE
		LEFT JOIN APPLYINFOMASTER AM
			ON AI.IPSIYEAR = AM.IPSIYEAR AND AI.IPSIGUBUN = AM.IPSIGUBUN AND AI.SUHUMNO = AM.SUHUMNO
		LEFT JOIN SELECTTYPEMODELMAJOR STMM
			ON STMM.IPSIYEAR = IM.IPSIYEAR AND STMM.IPSIGUBUN = IM.IPSIGUBUN AND STMM.MAJORCODE = IM.MAJORCODE
		LEFT JOIN SELECTTYPEMODEL STM
			ON STM.SMIDX = STMM.SMIDX 
	WHERE IM.IPSIYEAR = {입학연도} AND IM.IPSIGUBUN IN (8, 18) AND IM.ISUSE = 1 AND STM.PERSONNEL != 0
	GROUP BY IM.MAJORCODE
)
GROUP BY ROLLUP((MAJORCODE))
ORDER BY MAX(DISPLAYORDER), MAJORCODE