-- 7. 신입생모집 등록 현황(정시)_2025 이후
-- 정시
SELECT
		-- 합계(정원내)
		DECODE(GROUPING_ID(STM.IPSIYEAR, STM.IPSIGUBUN), 0, MAX(IM.MAJORNAME), '합계') AS 모집단위
		, SUM(CASE WHEN STM.SELTYPEGUBUN = 1 THEN STM.PERSONNEL END) AS 정원
		, SUM(CASE WHEN STM.SELTYPEGUBUN = 1 THEN APPLY_TOTAL END) AS 지원
		, SUM(CASE WHEN STM.SELTYPEGUBUN = 1 THEN IS_REG_TOTAL END) AS "등록(예정)"
		, SUM(CASE WHEN STM.SELTYPEGUBUN = 1 THEN STM.PERSONNEL - IS_REG_TOTAL END) AS 결원
		, SUM(CASE WHEN STM.SELTYPEGUBUN = 1 THEN IS_REFUND_TOTAL END) AS 합격환불
		, SUM(CASE WHEN STM.SELTYPEGUBUN = 1 THEN IS_GIVEUP_TOTAL + IS_UN_REG_TOTAL END) AS "예비포기+합격미등록"
		, SUM(CASE WHEN STM.SELTYPEGUBUN = 1 THEN IS_REMAIN_TOTAL END) AS 잔여
    , CASE
      WHEN SUM(CASE WHEN STM.SELTYPEGUBUN = 1 THEN STM.PERSONNEL END) = 0 THEN 0
      ELSE TRUNC(SUM(CASE WHEN STM.SELTYPEGUBUN = 1 THEN IS_REG_TOTAL END) / SUM(CASE WHEN STM.SELTYPEGUBUN = 1 THEN STM.PERSONNEL END) * 100, 1)
    END AS 등록률
		
		-- 일반고전형
		, SUM(CASE WHEN STM.SELTYPECODE = 1030 THEN STM.PERSONNEL END) AS 모집
		, SUM(CASE WHEN STM.SELTYPECODE = 1030 THEN APPLY_TOTAL END) AS 지원
		, SUM(CASE WHEN STM.SELTYPECODE = 1030 THEN IS_REG_TOTAL END) AS "등록(예정)"
		, SUM(CASE WHEN STM.SELTYPECODE = 1030 THEN STM.PERSONNEL - IS_REG_TOTAL END) AS 결원
		, SUM(CASE WHEN STM.SELTYPECODE = 1030 THEN IS_REFUND_TOTAL END) AS 합격환불
		, SUM(CASE WHEN STM.SELTYPECODE = 1030 THEN IS_GIVEUP_TOTAL + IS_UN_REG_TOTAL END) AS "예비포기+합격미등록"
		, SUM(CASE WHEN STM.SELTYPECODE = 1030 THEN IS_REMAIN_TOTAL END) AS 잔여
			
		-- 특성화고전형
		, SUM(CASE WHEN STM.SELTYPECODE = 1040 THEN STM.PERSONNEL END) AS 모집
		, SUM(CASE WHEN STM.SELTYPECODE = 1040 THEN APPLY_TOTAL END) AS 지원
		, SUM(CASE WHEN STM.SELTYPECODE = 1040 THEN IS_REG_TOTAL END) AS "등록(예정)"
		, SUM(CASE WHEN STM.SELTYPECODE = 1040 THEN STM.PERSONNEL - IS_REG_TOTAL END) AS 결원
		, SUM(CASE WHEN STM.SELTYPECODE = 1040 THEN IS_REFUND_TOTAL END) AS 합격환불
		, SUM(CASE WHEN STM.SELTYPECODE = 1040 THEN IS_GIVEUP_TOTAL + IS_UN_REG_TOTAL END) AS "예비포기+합격미등록"
		, SUM(CASE WHEN STM.SELTYPECODE = 1040 THEN IS_REMAIN_TOTAL END) AS 잔여

		-- 연계교육전형
		, SUM(CASE WHEN STM.SELTYPECODE = 1050 THEN STM.PERSONNEL END) AS 모집
		, SUM(CASE WHEN STM.SELTYPECODE = 1050 THEN APPLY_TOTAL END) AS 지원
		, SUM(CASE WHEN STM.SELTYPECODE = 1050 THEN IS_REG_TOTAL END) AS "등록(예정)"
		, SUM(CASE WHEN STM.SELTYPECODE = 1050 THEN STM.PERSONNEL - IS_REG_TOTAL END) AS 결원
		, SUM(CASE WHEN STM.SELTYPECODE = 1050 THEN IS_REFUND_TOTAL END) AS 합격환불
		, SUM(CASE WHEN STM.SELTYPECODE = 1050 THEN IS_GIVEUP_TOTAL + IS_UN_REG_TOTAL END) AS "예비포기+합격미등록"
		, SUM(CASE WHEN STM.SELTYPECODE = 1050 THEN IS_REMAIN_TOTAL END) AS 잔여
		
		-- 일반전형
		, SUM(CASE WHEN STM.SELTYPECODE = 1060 THEN STM.PERSONNEL END) AS 모집
		, SUM(CASE WHEN STM.SELTYPECODE = 1060 THEN APPLY_TOTAL END) AS 지원
		, SUM(CASE WHEN STM.SELTYPECODE = 1060 THEN IS_REG_TOTAL END) AS "등록(예정)"
		, SUM(CASE WHEN STM.SELTYPECODE = 1060 THEN STM.PERSONNEL - IS_REG_TOTAL END) AS 결원
		, SUM(CASE WHEN STM.SELTYPECODE = 1060 THEN IS_REFUND_TOTAL END) AS 합격환불
		, SUM(CASE WHEN STM.SELTYPECODE = 1060 THEN IS_GIVEUP_TOTAL + IS_UN_REG_TOTAL END) AS "예비포기+합격미등록"
		, SUM(CASE WHEN STM.SELTYPECODE = 1060 THEN IS_REMAIN_TOTAL END) AS 잔여

		-- 수능전형
		, SUM(CASE WHEN STM.SELTYPECODE = 1010 THEN STM.PERSONNEL END) AS 모집
		, SUM(CASE WHEN STM.SELTYPECODE = 1010 THEN APPLY_TOTAL END) AS 지원
		, SUM(CASE WHEN STM.SELTYPECODE = 1010 THEN IS_REG_TOTAL END) AS "등록(예정)"
		, SUM(CASE WHEN STM.SELTYPECODE = 1010 THEN STM.PERSONNEL - IS_REG_TOTAL END) AS 결원
		, SUM(CASE WHEN STM.SELTYPECODE = 1010 THEN IS_REFUND_TOTAL END) AS 합격환불
		, SUM(CASE WHEN STM.SELTYPECODE = 1010 THEN IS_GIVEUP_TOTAL + IS_UN_REG_TOTAL END) AS "예비포기+합격미등록"
		, SUM(CASE WHEN STM.SELTYPECODE = 1010 THEN IS_REMAIN_TOTAL END) AS 잔여
		
			-- 학생부전형
		, SUM(CASE WHEN STM.SELTYPECODE = 1020 THEN STM.PERSONNEL END) AS 모집
		, SUM(CASE WHEN STM.SELTYPECODE = 1020 THEN APPLY_TOTAL END) AS 지원
		, SUM(CASE WHEN STM.SELTYPECODE = 1020 THEN IS_REG_TOTAL END) AS "등록(예정)"
		, SUM(CASE WHEN STM.SELTYPECODE = 1020 THEN STM.PERSONNEL - IS_REG_TOTAL END) AS 결원
		, SUM(CASE WHEN STM.SELTYPECODE = 1020 THEN IS_REFUND_TOTAL END) AS 합격환불
		, SUM(CASE WHEN STM.SELTYPECODE = 1020 THEN IS_GIVEUP_TOTAL + IS_UN_REG_TOTAL END) AS "예비포기+합격미등록"
		, SUM(CASE WHEN STM.SELTYPECODE = 1020 THEN IS_REMAIN_TOTAL END) AS 잔여
		
		-- 합계(정원외)
		, SUM(CASE WHEN STM.SELTYPEGUBUN = 2 THEN STM.PERSONNEL END) AS 모집
		, SUM(CASE WHEN STM.SELTYPEGUBUN = 2 THEN APPLY_TOTAL END) AS 지원
		, SUM(CASE WHEN STM.SELTYPEGUBUN = 2 THEN IS_REG_TOTAL END) AS "등록(예정)"
		
		-- 전문대졸
		, SUM(CASE WHEN STM.SELTYPECODE = 2010 THEN STM.PERSONNEL END) AS 모집
		, SUM(CASE WHEN STM.SELTYPECODE = 2010 THEN APPLY_TOTAL END) AS 지원
		, SUM(CASE WHEN STM.SELTYPECODE = 2010 THEN IS_REG_TOTAL END) AS "등록(예정)"
		
		-- 농어촌
		, SUM(CASE WHEN STM.SELTYPECODE = 2020 THEN STM.PERSONNEL END) AS 모집
		, SUM(CASE WHEN STM.SELTYPECODE = 2020 THEN APPLY_TOTAL END) AS 지원
		, SUM(CASE WHEN STM.SELTYPECODE = 2020 THEN IS_REG_TOTAL END) AS "등록(예정)"
		
		-- 기초생활
		, SUM(CASE WHEN STM.SELTYPECODE = 2030 THEN STM.PERSONNEL END) AS 모집
		, SUM(CASE WHEN STM.SELTYPECODE = 2030 THEN APPLY_TOTAL END) AS 지원
		, SUM(CASE WHEN STM.SELTYPECODE = 2030 THEN IS_REG_TOTAL END) AS "등록(예정)"
		
		-- 서해5도
		, SUM(CASE WHEN STM.SELTYPECODE = 2040 THEN STM.PERSONNEL END) AS 모집
		, SUM(CASE WHEN STM.SELTYPECODE = 2040 THEN APPLY_TOTAL END) AS 지원
		, SUM(CASE WHEN STM.SELTYPECODE = 2040 THEN IS_REG_TOTAL END) AS "등록(예정)"
		
		-- 재직자
		, SUM(CASE WHEN STM.SELTYPECODE = 2060 THEN STM.PERSONNEL END) AS 모집
		, SUM(CASE WHEN STM.SELTYPECODE = 2060 THEN APPLY_TOTAL END) AS 지원
		, SUM(CASE WHEN STM.SELTYPECODE = 2060 THEN IS_REG_TOTAL END) AS "등록(예정)"
    
    -- 외국인/북한이탈주민
		, SUM(CASE WHEN STM.SELTYPECODE = 2070 THEN STM.PERSONNEL END) AS 모집
		, SUM(CASE WHEN STM.SELTYPECODE = 2070 THEN APPLY_TOTAL END) AS 지원
		, SUM(CASE WHEN STM.SELTYPECODE = 2070 THEN IS_REG_TOTAL END) AS "등록(예정)"
    
    -- 재외국민
		, SUM(CASE WHEN STM.SELTYPECODE = 2080 THEN STM.PERSONNEL END) AS 모집
		, SUM(CASE WHEN STM.SELTYPECODE = 2080 THEN APPLY_TOTAL END) AS 지원
		, SUM(CASE WHEN STM.SELTYPECODE = 2080 THEN IS_REG_TOTAL END) AS "등록(예정)"

FROM VWSELECTTYPEMODEL STM
LEFT JOIN INFOIPSI II ON STM.IPSIYEAR = II.IPSIYEAR AND STM.IPSIGUBUN = II.IPSIGUBUN
LEFT JOIN INFOMAJOR IM ON STM.IPSIYEAR = IM.IPSIYEAR AND STM.IPSIGUBUN = IM.IPSIGUBUN
  AND STM.MAJORCODE = IM.MAJORCODE
LEFT JOIN (
    SELECT AI.IPSIYEAR, AI.IPSIGUBUN, AI.GUNID, AI.SELTYPECODE, AI.MAJORCODE
    , COUNT(*) AS APPLY_TOTAL -- 지원인원
    , SUM(CASE WHEN AM.LASTISPASS = 0 AND AM.ISPASSGIVEUP = 1 THEN 1 ELSE 0 END) AS IS_GIVEUP_TOTAL -- 포기인원
    , SUM(CASE WHEN AM.LASTISPASS = 0 AND AM.ISREG = 0 THEN 1 ELSE 0 END) AS IS_UN_REG_TOTAL -- 미등록
    , SUM(CASE WHEN AM.LASTISPASS = 1 AND AM.ISREG = 1 AND (AM.ISREFUND = 0 OR AM.ISREFUND IS NULL) THEN 1 ELSE 0 END) AS IS_REG_TOTAL -- 등록인원
    , SUM(CASE WHEN AM.ISREG = 1 AND AM.ISREFUND = 1 THEN 1 ELSE 0 END) AS IS_REFUND_TOTAL -- 환불인원
    , SUM(CASE WHEN AM.PASSSTEP IS NULL AND AM.SPARERANK > 0 THEN 1 ELSE 0 END) + SUM(CASE WHEN AM.ISSAJUNG = 0 THEN 1 ELSE 0 END) AS IS_REMAIN_TOTAL -- 잔여인원(사정제외자 포함)
    FROM APPLYINFO AI 
    	LEFT JOIN APPLYINFOMASTER AM ON AI.IPSIYEAR = AM.IPSIYEAR AND AI.IPSIGUBUN = AM.IPSIGUBUN AND AI.SUHUMNO = AM.SUHUMNO
    GROUP BY AI.IPSIYEAR, AI.IPSIGUBUN, AI.GUNID, AI.SELTYPECODE, AI.MAJORCODE
) AI ON STM.IPSIYEAR = AI.IPSIYEAR AND STM.IPSIGUBUN = AI.IPSIGUBUN
    AND STM.SELTYPECODE = AI.SELTYPECODE AND STM.MAJORCODE = AI.MAJORCODE
WHERE STM.IPSIYEAR = {입학연도} AND STM.IPSIGUBUN = 3 AND II.ISSIMUL = 0
GROUP BY ROLLUP((STM.IPSIYEAR, STM.IPSIGUBUN, STM.MAJORCODE))
ORDER BY STM.IPSIYEAR, STM.IPSIGUBUN, MAX(STM.MAJORORDER), STM.MAJORCODE