-- 9. 신입생모집 등록 현황(전문학사과정)
-- 수시1차, 수시2차, 정시, 자율
-- 예치금등록 또는 본등록 기간이 아닌 경우 모집단위 열을 제외한 모든 열을 null 값이 나오도록 했다.

SELECT
		-- 합계(정원내)
		DECODE(GROUPING_ID(STM.IPSIYEAR), 0, MAX(IM.MAJORNAME), '합계') AS 모집단위
		, CASE 
			WHEN MAX(C500.CODENAME) IS NULL THEN NULL
			ELSE SUM(CASE WHEN STM.SELTYPEGUBUN = 1 THEN STM.PERSONNEL END)
		END AS 정원
		, CASE 
			WHEN MAX(C500.CODENAME) IS NULL THEN NULL
			ELSE SUM(CASE WHEN STM.SELTYPEGUBUN = 1 THEN APPLY_TOTAL END) 
		END AS 지원
		, SUM(CASE
	  	WHEN STM.SELTYPEGUBUN = 1 AND C500.CODEIDX = 1 THEN IS_DEPOSIT_TOTAL -- C500.CODEIDX = 1 : 예치금 등록 기간이면, 
			WHEN STM.SELTYPEGUBUN = 1 AND C500.CODEIDX = 2 THEN IS_REG_TOTAL -- C500.CODEIDX = 2 : 본 등록 기간이면, 
		END) AS "등록(예정)"
		, CASE 
			WHEN MAX(C500.CODENAME) IS NULL THEN NULL
			ELSE SUM(CASE WHEN STM.SELTYPEGUBUN = 1 THEN STM.PERSONNEL END) - SUM(CASE
		  	WHEN STM.SELTYPEGUBUN = 1 AND C500.CODEIDX = 1 THEN IS_DEPOSIT_TOTAL
				WHEN STM.SELTYPEGUBUN = 1 AND C500.CODEIDX = 2 THEN IS_REG_TOTAL
				ELSE 0
			END)
		END AS 결원
		, SUM(CASE
			WHEN STM.SELTYPEGUBUN = 1 AND C500.CODEIDX = 1 THEN IS_DEPOSIT_REFUND_TOTAL
			WHEN STM.SELTYPEGUBUN = 1 AND C500.CODEIDX = 2 THEN IS_REG_REFUND_TOTAL
		END) AS 합격환불
		, CASE 
			WHEN MAX(C500.CODENAME) IS NULL THEN NULL
			ELSE SUM(CASE WHEN STM.SELTYPEGUBUN = 1 THEN IS_GIVEUP_TOTAL + IS_UN_DEPOSIT_TOTAL END)
		END AS "예비포기+합격미등록"
		, CASE 
			WHEN MAX(C500.CODENAME) IS NULL THEN NULL
			ELSE SUM(CASE WHEN STM.SELTYPEGUBUN = 1 THEN IS_REMAIN_TOTAL END)
		END AS 잔여
		, CASE
      WHEN SUM(CASE WHEN STM.SELTYPEGUBUN = 1 THEN STM.PERSONNEL END) = 0 THEN 0
      ELSE TRUNC(SUM(CASE
	  	WHEN STM.SELTYPEGUBUN = 1 AND C500.CODEIDX = 1 THEN IS_DEPOSIT_TOTAL
			WHEN STM.SELTYPEGUBUN = 1 AND C500.CODEIDX = 2 THEN IS_REG_TOTAL
		END) / SUM(CASE WHEN STM.SELTYPEGUBUN = 1 THEN STM.PERSONNEL END) * 100 , 1)
    END AS 등록률
		
		-- 일반고전형
		, CASE 
			WHEN MAX(C500.CODENAME) IS NULL THEN NULL
			ELSE SUM(CASE WHEN STM.SELTYPECODE = 1030 THEN STM.PERSONNEL END)
		END AS 모집
		, CASE 
			WHEN MAX(C500.CODENAME) IS NULL THEN NULL
			ELSE SUM(CASE WHEN STM.SELTYPECODE = 1030 THEN APPLY_TOTAL END)
		END AS 지원
		, SUM(CASE
	  	WHEN STM.SELTYPECODE = 1030 AND C500.CODEIDX = 1 THEN IS_DEPOSIT_TOTAL
			WHEN STM.SELTYPECODE = 1030 AND C500.CODEIDX = 2 THEN IS_REG_TOTAL
		END) AS "등록(예정)"
		, CASE 
			WHEN MAX(C500.CODENAME) IS NULL THEN NULL
			ELSE SUM(CASE WHEN STM.SELTYPECODE = 1030 THEN STM.PERSONNEL END) - SUM(CASE
		  	WHEN STM.SELTYPECODE = 1030 AND C500.CODEIDX = 1 THEN IS_DEPOSIT_TOTAL
				WHEN STM.SELTYPECODE = 1030 AND C500.CODEIDX = 2 THEN IS_REG_TOTAL 
				ELSE 0
			END)
		END AS 결원
		, SUM(CASE
			WHEN STM.SELTYPECODE = 1030 AND C500.CODEIDX = 1 THEN IS_DEPOSIT_REFUND_TOTAL
			WHEN STM.SELTYPECODE = 1030 AND C500.CODEIDX = 2 THEN IS_REG_REFUND_TOTAL
		END) AS 합격환불
		, CASE 
			WHEN MAX(C500.CODENAME) IS NULL THEN NULL
			ELSE SUM(CASE WHEN STM.SELTYPECODE = 1030 THEN IS_GIVEUP_TOTAL + IS_UN_DEPOSIT_TOTAL END)
		END AS "예비포기+합격미등록"
		, CASE 
			WHEN MAX(C500.CODENAME) IS NULL THEN NULL
			ELSE SUM(CASE WHEN STM.SELTYPECODE = 1030 THEN IS_REMAIN_TOTAL END)
		END AS 잔여
			
		-- 특성화고전형
		, CASE 
			WHEN MAX(C500.CODENAME) IS NULL THEN NULL
			ELSE SUM(CASE WHEN STM.SELTYPECODE = 1040 THEN STM.PERSONNEL END)
		END AS 모집
		, CASE 
			WHEN MAX(C500.CODENAME) IS NULL THEN NULL
			ELSE SUM(CASE WHEN STM.SELTYPECODE = 1040 THEN APPLY_TOTAL END)
		END AS 지원
		, SUM(CASE
	  	WHEN STM.SELTYPECODE = 1040 AND C500.CODEIDX = 1 THEN IS_DEPOSIT_TOTAL
			WHEN STM.SELTYPECODE = 1040 AND C500.CODEIDX = 2 THEN IS_REG_TOTAL
		END) AS "등록(예정)"
		, CASE 
			WHEN MAX(C500.CODENAME) IS NULL THEN NULL
			ELSE SUM(CASE WHEN STM.SELTYPECODE = 1040 THEN STM.PERSONNEL END) - SUM(CASE
		  	WHEN STM.SELTYPECODE = 1040 AND C500.CODEIDX = 1 THEN IS_DEPOSIT_TOTAL
				WHEN STM.SELTYPECODE = 1040 AND C500.CODEIDX = 2 THEN IS_REG_TOTAL 
				ELSE 0
			END)
		END AS 결원
		, SUM(CASE
			WHEN STM.SELTYPECODE = 1040 AND C500.CODEIDX = 1 THEN IS_DEPOSIT_REFUND_TOTAL
			WHEN STM.SELTYPECODE = 1040 AND C500.CODEIDX = 2 THEN IS_REG_REFUND_TOTAL
		END) AS 합격환불
		, CASE 
			WHEN MAX(C500.CODENAME) IS NULL THEN NULL
			ELSE SUM(CASE WHEN STM.SELTYPECODE = 1040 THEN IS_GIVEUP_TOTAL + IS_UN_DEPOSIT_TOTAL END)
		END AS "예비포기+합격미등록"
		, CASE 
			WHEN MAX(C500.CODENAME) IS NULL THEN NULL
			ELSE SUM(CASE WHEN STM.SELTYPECODE = 1040 THEN IS_REMAIN_TOTAL END)
		END AS 잔여
		
		-- 연계교육전형
		, CASE 
			WHEN MAX(C500.CODENAME) IS NULL THEN NULL
			ELSE SUM(CASE WHEN STM.SELTYPECODE = 1050 THEN STM.PERSONNEL END)
		END AS 모집
		, CASE 
			WHEN MAX(C500.CODENAME) IS NULL THEN NULL
			ELSE SUM(CASE WHEN STM.SELTYPECODE = 1050 THEN APPLY_TOTAL END)
		END AS 지원
		, SUM(CASE
	  	WHEN STM.SELTYPECODE = 1050 AND C500.CODEIDX = 1 THEN IS_DEPOSIT_TOTAL
			WHEN STM.SELTYPECODE = 1050 AND C500.CODEIDX = 2 THEN IS_REG_TOTAL
		END) AS "등록(예정)"
		, CASE 
			WHEN MAX(C500.CODENAME) IS NULL THEN NULL
			ELSE SUM(CASE WHEN STM.SELTYPECODE = 1050 THEN STM.PERSONNEL END) - SUM(CASE
		  	WHEN STM.SELTYPECODE = 1050 AND C500.CODEIDX = 1 THEN IS_DEPOSIT_TOTAL
				WHEN STM.SELTYPECODE = 1050 AND C500.CODEIDX = 2 THEN IS_REG_TOTAL 
				ELSE 0
			END)
		END AS 결원
		, SUM(CASE
			WHEN STM.SELTYPECODE = 1050 AND C500.CODEIDX = 1 THEN IS_DEPOSIT_REFUND_TOTAL
			WHEN STM.SELTYPECODE = 1050 AND C500.CODEIDX = 2 THEN IS_REG_REFUND_TOTAL
		END) AS 합격환불
		, CASE 
			WHEN MAX(C500.CODENAME) IS NULL THEN NULL
			ELSE SUM(CASE WHEN STM.SELTYPECODE = 1050 THEN IS_GIVEUP_TOTAL + IS_UN_DEPOSIT_TOTAL END)
		END AS "예비포기+합격미등록"
		, CASE 
			WHEN MAX(C500.CODENAME) IS NULL THEN NULL
			ELSE SUM(CASE WHEN STM.SELTYPECODE = 1050 THEN IS_REMAIN_TOTAL END)
		END AS 잔여
		
		-- 일반전형
		, CASE 
			WHEN MAX(C500.CODENAME) IS NULL THEN NULL
			ELSE SUM(CASE WHEN STM.SELTYPECODE = 1060 THEN STM.PERSONNEL END)
		END AS 모집
		, CASE 
			WHEN MAX(C500.CODENAME) IS NULL THEN NULL
			ELSE SUM(CASE WHEN STM.SELTYPECODE = 1060 THEN APPLY_TOTAL END)
		END AS 지원
		, SUM(CASE
	  	WHEN STM.SELTYPECODE = 1060 AND C500.CODEIDX = 1 THEN IS_DEPOSIT_TOTAL
			WHEN STM.SELTYPECODE = 1060 AND C500.CODEIDX = 2 THEN IS_REG_TOTAL
		END) AS "등록(예정)"
		, CASE 
			WHEN MAX(C500.CODENAME) IS NULL THEN NULL
			ELSE SUM(CASE WHEN STM.SELTYPECODE = 1060 THEN STM.PERSONNEL END) - SUM(CASE
		  	WHEN STM.SELTYPECODE = 1060 AND C500.CODEIDX = 1 THEN IS_DEPOSIT_TOTAL
				WHEN STM.SELTYPECODE = 1060 AND C500.CODEIDX = 2 THEN IS_REG_TOTAL 
				ELSE 0
			END)
		END AS 결원
		, SUM(CASE
			WHEN STM.SELTYPECODE = 1060 AND C500.CODEIDX = 1 THEN IS_DEPOSIT_REFUND_TOTAL
			WHEN STM.SELTYPECODE = 1060 AND C500.CODEIDX = 2 THEN IS_REG_REFUND_TOTAL
		END) AS 합격환불
		, CASE 
			WHEN MAX(C500.CODENAME) IS NULL THEN NULL
			ELSE SUM(CASE WHEN STM.SELTYPECODE = 1060 THEN IS_GIVEUP_TOTAL + IS_UN_DEPOSIT_TOTAL END)
		END AS "예비포기+합격미등록"
		, CASE 
			WHEN MAX(C500.CODENAME) IS NULL THEN NULL
			ELSE SUM(CASE WHEN STM.SELTYPECODE = 1060 THEN IS_REMAIN_TOTAL END)
		END AS 잔여

		-- 수능전형
		, CASE 
			WHEN MAX(C500.CODENAME) IS NULL THEN NULL
			ELSE SUM(CASE WHEN STM.SELTYPECODE = 1010 THEN STM.PERSONNEL END)
		END AS 모집
		, CASE 
			WHEN MAX(C500.CODENAME) IS NULL THEN NULL
			ELSE SUM(CASE WHEN STM.SELTYPECODE = 1010 THEN APPLY_TOTAL END)
		END AS 지원
		, SUM(CASE
	  	WHEN STM.SELTYPECODE = 1010 AND C500.CODEIDX = 1 THEN IS_DEPOSIT_TOTAL
			WHEN STM.SELTYPECODE = 1010 AND C500.CODEIDX = 2 THEN IS_REG_TOTAL
		END) AS "등록(예정)"
		, CASE 
			WHEN MAX(C500.CODENAME) IS NULL THEN NULL
			ELSE SUM(CASE WHEN STM.SELTYPECODE = 1010 THEN STM.PERSONNEL END) - SUM(CASE
		  	WHEN STM.SELTYPECODE = 1010 AND C500.CODEIDX = 1 THEN IS_DEPOSIT_TOTAL
				WHEN STM.SELTYPECODE = 1010 AND C500.CODEIDX = 2 THEN IS_REG_TOTAL 
				ELSE 0
			END)
		END AS 결원
		, SUM(CASE
			WHEN STM.SELTYPECODE = 1010 AND C500.CODEIDX = 1 THEN IS_DEPOSIT_REFUND_TOTAL
			WHEN STM.SELTYPECODE = 1010 AND C500.CODEIDX = 2 THEN IS_REG_REFUND_TOTAL
		END) AS 합격환불
		, CASE 
			WHEN MAX(C500.CODENAME) IS NULL THEN NULL
			ELSE SUM(CASE WHEN STM.SELTYPECODE = 1010 THEN IS_GIVEUP_TOTAL + IS_UN_DEPOSIT_TOTAL END)
		END AS "예비포기+합격미등록"
		, CASE 
			WHEN MAX(C500.CODENAME) IS NULL THEN NULL
			ELSE SUM(CASE WHEN STM.SELTYPECODE = 1010 THEN IS_REMAIN_TOTAL END)
		END AS 잔여
		
			-- 학생부전형
		, CASE 
			WHEN MAX(C500.CODENAME) IS NULL THEN NULL
			ELSE SUM(CASE WHEN STM.SELTYPECODE = 1020 THEN STM.PERSONNEL END)
		END AS 모집
		, CASE 
			WHEN MAX(C500.CODENAME) IS NULL THEN NULL
			ELSE SUM(CASE WHEN STM.SELTYPECODE = 1020 THEN APPLY_TOTAL END)
		END AS 지원
		, SUM(CASE
			WHEN STM.SELTYPECODE = 1020 AND C500.CODEIDX = 1 THEN IS_DEPOSIT_TOTAL
			WHEN STM.SELTYPECODE = 1020 AND C500.CODEIDX = 2 THEN IS_REG_TOTAL
		END) AS "등록(예정)"
		, CASE 
			WHEN MAX(C500.CODENAME) IS NULL THEN NULL
			ELSE SUM(CASE WHEN STM.SELTYPECODE = 1020 THEN STM.PERSONNEL END) - SUM(CASE
		  	WHEN STM.SELTYPECODE = 1020 AND C500.CODEIDX = 1 THEN IS_DEPOSIT_TOTAL
				WHEN STM.SELTYPECODE = 1020 AND C500.CODEIDX = 2 THEN IS_REG_TOTAL 
				ELSE 0
			END)
		END AS 결원
		, SUM(CASE
			WHEN STM.SELTYPECODE = 1020 AND C500.CODEIDX = 1 THEN IS_DEPOSIT_REFUND_TOTAL
			WHEN STM.SELTYPECODE = 1020 AND C500.CODEIDX = 2 THEN IS_REG_REFUND_TOTAL
			
		END) AS 합격환불
		, CASE 
			WHEN MAX(C500.CODENAME) IS NULL THEN NULL
			ELSE SUM(CASE WHEN STM.SELTYPECODE = 1020 THEN IS_GIVEUP_TOTAL + IS_UN_DEPOSIT_TOTAL END)
		END AS "예비포기+합격미등록"
		, CASE 
			WHEN MAX(C500.CODENAME) IS NULL THEN NULL
			ELSE SUM(CASE WHEN STM.SELTYPECODE = 1020 THEN IS_REMAIN_TOTAL END)
		END AS 잔여
		
		-- 합계(정원외)
		, CASE 
			WHEN MAX(C500.CODENAME) IS NULL THEN NULL
			ELSE SUM(CASE WHEN STM.SELTYPEGUBUN = 2 THEN STM.PERSONNEL END)
		END AS 모집
		, CASE 
			WHEN MAX(C500.CODENAME) IS NULL THEN NULL
			ELSE SUM(CASE WHEN STM.SELTYPEGUBUN = 2 THEN APPLY_TOTAL END)
		END AS 지원
		, SUM(CASE
			WHEN STM.SELTYPEGUBUN = 2 AND C500.CODEIDX = 1 THEN IS_DEPOSIT_TOTAL
			WHEN STM.SELTYPEGUBUN = 2 AND C500.CODEIDX = 2 THEN IS_REG_TOTAL
		END) AS "등록(예정)"
		
		-- 전문대졸
		, CASE 
			WHEN MAX(C500.CODENAME) IS NULL THEN NULL
			ELSE SUM(CASE WHEN STM.SELTYPECODE = 2010 THEN STM.PERSONNEL END)
		END AS 모집
		, CASE 
			WHEN MAX(C500.CODENAME) IS NULL THEN NULL
			ELSE SUM(CASE WHEN STM.SELTYPECODE = 2010 THEN APPLY_TOTAL END)
		END AS 지원
		, SUM(CASE
			WHEN STM.SELTYPECODE = 2010 AND C500.CODEIDX = 1 THEN IS_DEPOSIT_TOTAL
			WHEN STM.SELTYPECODE = 2010 AND C500.CODEIDX = 2 THEN IS_REG_TOTAL
		END) AS "등록(예정)"
		
		-- 농어촌
		, CASE 
			WHEN MAX(C500.CODENAME) IS NULL THEN NULL
			ELSE SUM(CASE WHEN STM.SELTYPECODE = 2020 THEN STM.PERSONNEL END)
		END AS 모집
		, CASE 
			WHEN MAX(C500.CODENAME) IS NULL THEN NULL
			ELSE SUM(CASE WHEN STM.SELTYPECODE = 2020 THEN APPLY_TOTAL END)
		END AS 지원
		, SUM(CASE
			WHEN STM.SELTYPECODE = 2020 AND C500.CODEIDX = 1 THEN IS_DEPOSIT_TOTAL
			WHEN STM.SELTYPECODE = 2020 AND C500.CODEIDX = 2 THEN IS_REG_TOTAL
		END) AS "등록(예정)"
		
		-- 기초생활
		, CASE 
			WHEN MAX(C500.CODENAME) IS NULL THEN NULL
			ELSE SUM(CASE WHEN STM.SELTYPECODE = 2030 THEN STM.PERSONNEL END)
		END AS 모집
		, CASE 
			WHEN MAX(C500.CODENAME) IS NULL THEN NULL
			ELSE SUM(CASE WHEN STM.SELTYPECODE = 2030 THEN APPLY_TOTAL END)
		END AS 지원
		, SUM(CASE
			WHEN STM.SELTYPECODE = 2030 AND C500.CODEIDX = 1 THEN IS_DEPOSIT_TOTAL
			WHEN STM.SELTYPECODE = 2030 AND C500.CODEIDX = 2 THEN IS_REG_TOTAL
		END) AS "등록(예정)"
		
		-- 서해5도
		, CASE 
			WHEN MAX(C500.CODENAME) IS NULL THEN NULL
			ELSE SUM(CASE WHEN STM.SELTYPECODE = 2040 THEN STM.PERSONNEL END)
		END AS 모집
		, CASE 
			WHEN MAX(C500.CODENAME) IS NULL THEN NULL
			ELSE SUM(CASE WHEN STM.SELTYPECODE = 2040 THEN APPLY_TOTAL END)
		END AS 지원
		, SUM(CASE
			WHEN STM.SELTYPECODE = 2040 AND C500.CODEIDX = 1 THEN IS_DEPOSIT_TOTAL
			WHEN STM.SELTYPECODE = 2040 AND C500.CODEIDX = 2 THEN IS_REG_TOTAL
		END) AS "등록(예정)"
		
		-- 외국인/북한이탈주민
		, CASE 
			WHEN MAX(C500.CODENAME) IS NULL THEN NULL
			ELSE SUM(CASE WHEN STM.SELTYPECODE = 2070 THEN STM.PERSONNEL END)
		END AS 모집
		, CASE 
			WHEN MAX(C500.CODENAME) IS NULL THEN NULL
			ELSE SUM(CASE WHEN STM.SELTYPECODE = 2070 THEN APPLY_TOTAL END)
		END AS 지원
		, SUM(CASE
			WHEN STM.SELTYPECODE = 2070 AND C500.CODEIDX = 1 THEN IS_DEPOSIT_TOTAL
			WHEN STM.SELTYPECODE = 2070 AND C500.CODEIDX = 2 THEN IS_REG_TOTAL
		END) AS "등록(예정)"
		
		-- 재직자
		, CASE 
			WHEN MAX(C500.CODENAME) IS NULL THEN NULL
			ELSE SUM(CASE WHEN STM.SELTYPECODE = 2060 THEN STM.PERSONNEL END)
		END AS 모집
		, CASE 
			WHEN MAX(C500.CODENAME) IS NULL THEN NULL
			ELSE SUM(CASE WHEN STM.SELTYPECODE = 2060 THEN APPLY_TOTAL END)
		END AS 지원
		, SUM(CASE
			WHEN STM.SELTYPECODE = 2060 AND C500.CODEIDX = 1 THEN IS_DEPOSIT_TOTAL
			WHEN STM.SELTYPECODE = 2060 AND C500.CODEIDX = 2 THEN IS_REG_TOTAL
		END) AS "등록(예정)"

FROM VWSELECTTYPEMODEL STM
LEFT JOIN INFOIPSI II ON STM.IPSIYEAR = II.IPSIYEAR AND STM.IPSIGUBUN = II.IPSIGUBUN
LEFT JOIN INFOMAJOR IM ON STM.IPSIYEAR = IM.IPSIYEAR AND STM.IPSIGUBUN = IM.IPSIGUBUN
  AND STM.MAJORCODE = IM.MAJORCODE
LEFT JOIN (
    SELECT AI.IPSIYEAR, AI.IPSIGUBUN, AI.GUNID, AI.SELTYPECODE, AI.MAJORCODE
    , COUNT(*) AS APPLY_TOTAL -- 지원인원
    , SUM(CASE WHEN AM.LASTISPASS = 0 AND AM.ISPASSGIVEUP = 1 THEN 1 ELSE 0 END) AS IS_GIVEUP_TOTAL -- 포기인원
    , SUM(CASE WHEN AM.LASTISPASS = 0 AND AM.ISDEPOSIT = 0 THEN 1 ELSE 0 END) AS IS_UN_DEPOSIT_TOTAL -- 미등록
    , SUM(CASE WHEN AM.LASTISPASS = 1 AND AM.ISDEPOSIT = 1 AND (AM.ISREFUND = 0 OR AM.ISREFUND IS NULL) THEN 1 ELSE 0 END) AS IS_DEPOSIT_TOTAL -- 예치금등록인원
    , SUM(CASE WHEN AM.LASTISPASS = 1 AND AM.ISREG = 1 AND (AM.ISREFUND = 0 OR AM.ISREFUND IS NULL) THEN 1 ELSE 0 END) AS IS_REG_TOTAL -- 본등록등록인원
    , SUM(CASE WHEN AM.ISDEPOSIT = 1 AND AM.ISREFUND = 1 THEN 1 ELSE 0 END) AS IS_DEPOSIT_REFUND_TOTAL -- 예치금환불인원
    , SUM(CASE WHEN AM.ISREG = 1 AND AM.ISREFUND = 1 THEN 1 ELSE 0 END) AS IS_REG_REFUND_TOTAL -- 본등록환불인원
    , SUM(CASE WHEN AM.PASSSTEP IS NULL AND AM.SPARERANK > 0 THEN 1 ELSE 0 END) + SUM(CASE WHEN AM.ISSAJUNG = 0 THEN 1 ELSE 0 END) AS IS_REMAIN_TOTAL -- 잔여인원(사정제외자 포함)
    FROM APPLYINFO AI 
    	LEFT JOIN APPLYINFOMASTER AM ON AI.IPSIYEAR = AM.IPSIYEAR AND AI.IPSIGUBUN = AM.IPSIGUBUN AND AI.SUHUMNO = AM.SUHUMNO
    GROUP BY AI.IPSIYEAR, AI.IPSIGUBUN, AI.GUNID, AI.SELTYPECODE, AI.MAJORCODE
) AI ON STM.IPSIYEAR = AI.IPSIYEAR AND STM.IPSIGUBUN = AI.IPSIGUBUN
    AND STM.SELTYPECODE = AI.SELTYPECODE AND STM.MAJORCODE = AI.MAJORCODE
LEFT JOIN CODEYEAR C500
	ON C500.CODEGUBUN = 500
		AND STM.IPSIYEAR = C500.IPSIYEAR
		AND TO_DATE(C500.BIGO1, 'YYYY-MM-DD HH24:MI:SS') < SYSDATE AND SYSDATE <= TO_DATE(C500.BIGO2, 'YYYY-MM-DD HH24:MI:SS') -- 예치금 등록 기간 또는 본 등록 기간 날짜 체크 
WHERE STM.IPSIYEAR = {입학연도} AND II.IpsiScope = 1 AND II.ISSIMUL = 0
GROUP BY ROLLUP((STM.IPSIYEAR, STM.MAJORCODE))
ORDER BY STM.IPSIYEAR, MAX(STM.MAJORORDER), STM.MAJORCODE